spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?serverTimezone=Asia/Seoul
    username: root
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  data:
    mongodb:
      uri: mongodb://user:user@localhost:27017/platform?authSource=admin&authenticationDatabase=admin


external-server:
  metadata:
    url: http://localhost:8088
